Adding svelte
NixNeovim/NixNeovim pull request #67
Opened 2023-06-19 04:52 UTC by TornaxO7

Adds the svelte LSP server.

I hope that I added everything which is needed?

2023-06-19 05:04 UTC, TornaxO7 commented
I'm unsure how to test this, may I ask for your hepl here?

2023-06-20 07:55 UTC, jooooscha commented
Thanks for your contribution.

The lsp test is not very sophisticated right now. You only have to enable the lsp in `tests/plugins/lsp.nix` and add the svelte language to the bash array like this at the bottom of `lsp.nix`

```bash
for lang in rust c nix svelte
do 
...
done
```

2023-06-20 07:57 UTC, TornaxO7 commented
Thank you for the explanation! I'll try it out later.

2023-06-21 08:49 UTC, jooooscha requested changes

2023-06-21 08:49 UTC, jooooscha commented on plugins/nvim-lsp/options/servers.nix
> +      serverName = "svelteserver";
The correct server name appears to be `svelte` not `svelteserver`.  It is listed as such in [lspconfig](https://github.com/neovim/nvim-lspconfig/tree/master/lua/lspconfig/server_configurations)

2023-06-21 08:49 UTC, jooooscha commented on tests/plugins/lsp.nix
You stlil need to add `svelte-language-server` to the enabled servers.

And you have to add the correct lua output to the assertDiff function in `nmt.script`.
I should be after the config for rust-analyzer.

You can run `nix flake check -L` locally, and it will tell you the missing output.

2023-06-21 15:34 UTC, TornaxO7 commented on tests/plugins/lsp.nix
> You stlil need to add svelte-language-server to the enabled servers.

May I ask how I can do this?

2023-06-22 10:32 UTC, jooooscha commented on tests/plugins/lsp.nix
just like the other servers here: https://github.com/NixNeovim/NixNeovim/pull/67/files#diff-6aa1933dc0d21f52e72bd51ef584e81a0b401a7797dc74bbc2aa5b685248ed72L14-L22

2024-01-07 12:57 UTC, TornaxO7 commented
oh sorry, I don't work on this anymore, so we can close this.

2024-01-08 10:15 UTC, jooooscha commented
implemented in 5f851526d74ad28bb6226a07114b5239980d975b

2024-01-08 10:15 UTC, closed without merging