Add typescript lsp
NixNeovim/NixNeovim pull request #68
Opened 2023-06-19 04:54 UTC by TornaxO7

Adds the typescript-language-server

2023-06-19 05:05 UTC, TornaxO7 commented
I don't understand why it fails.

2023-06-20 07:59 UTC, jooooscha commented
The error seems to be a fault with the github action. I currently do not have the time or knowledge to debug this. Please ignore for now :D

Could you expand test test as in #67? Thanks :)

2023-06-21 08:59 UTC, jooooscha requested changes

2023-06-21 08:59 UTC, jooooscha commented on plugins/nvim-lsp/options/servers.nix
> +      packages = [ nodePackages.typescript-language-server ];
The `serverName` should be tsserver

2023-06-21 08:59 UTC, jooooscha commented on tests/plugins/lsp.nix
As with your other PR, you need to add the typescript-language-server to the servers list and add the missing output to the assertDiff function

2024-01-06 23:39 UTC, closed without merging

2024-01-08 10:21 UTC, jooooscha commented
Implemented in b8d4b01aa7d6f500034a9bd79811b6053dc6771c